### ISSUE TITLE
Uptime issue

### ISSUE THREAD

**Issue by nizomovasadbek** [ae5259/xifetch-rs#1]
![image](https://github.com/triistam/xifetch-rs/assets/48754111/cdef62fa-55ba-4783-8f23-cbf45b43b330)
Uptime o'rniga hozirgi vaqtni display qilebdi

**Comment by aelloc** [comment]
Issue uchun raxmat!

Kodda o'zgarish qilindi, lekin `cargo publish` bilan muammo bo'lgani uchun hali crates.io ga chiqarilmadi.

**Comment by aelloc** [comment]
[crates](https://crates.io) saytiga muvoffaqiyatli push qilindi.

Issue uchun raxmat!!

xifetch: https://crates.io/crates/xifetch

**Comment by aelloc** [comment]
endi bu issue ni yopsa xam bo'ladi
